FROM postgres

USER postgres
WORKDIR /app

COPY src/test/sql/car-db-ddl.sql /docker-entrypoint-initdb.d/1_create-car.sql
COPY src/test/sql/car-db-dml.sql /docker-entrypoint-initdb.d/2_insert-car-test-data.sql

COPY --chown=postgres:postgres ./src/test/docker/wait-for-postgres.sh ./bin/wait-for-postgres.sh
RUN chmod +x ./bin/wait-for-postgres.sh

EXPOSE 5432
